[package]
name = "rust-rpc"
version = "0.1.0"
authors = ["Gaurang Tandon <gaurang.tandon@students.iiit.ac.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
